INSERT INTO media (
    id,
    is_adult,
    media_status,
    season,
    season_year,
    average_score,
    site_url,
    title_english,
    title_native,
    title_romaji,
    synonyms,
    format,
    description,
    start_date,
    end_date,
    updated_at,
    episodes,
    country_of_origin,
    cover_url,
    genres,
    studios,
    producers
)
VALUES (
    :id,
    :is_adult,
    :media_status,
    :season,
    :season_year,
    :average_score,
    :site_url,
    :title_english,
    :title_native,
    :title_romaji,
    :synonyms,
    :format,
    :description,
    :start_date,
    :end_date,
    :updated_at,
    :episodes,
    :country_of_origin,
    :cover_url,
    :genres,
    :studios,
    :producers
)
ON CONFLICT(id) DO UPDATE SET
    is_adult = excluded.is_adult,
    media_status = excluded.media_status,
    season = excluded.season,
    season_year = excluded.season_year,
    average_score = excluded.average_score,
    site_url = excluded.site_url,
    title_english = excluded.title_english,
    title_native = excluded.title_native,
    title_romaji = excluded.title_romaji,
    synonyms = excluded.synonyms,
    format = excluded.format,
    description = excluded.description,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    updated_at = excluded.updated_at,
    episodes = excluded.episodes,
    country_of_origin = excluded.country_of_origin,
    cover_url = excluded.cover_url,
    genres = excluded.genres,
    studios = excluded.studios,
    producers = excluded.producers;

