qt_add_executable(AniTrack
    app/app.cpp
    app/app.hpp
    app/app_config.hpp
    app/app_controller.cpp
    app/app_controller.hpp
    app/app_resources.hpp
    app/command_line_parser.cpp
    app/command_line_parser.hpp
    app/system_tray_icon.cpp
    app/system_tray_icon.hpp
    base/account/account_manager.cpp
    base/account/account_manager.hpp
    base/anilist/anilist_account.cpp
    base/anilist/anilist_account.hpp
    base/anilist/anilist_anime.hpp
    base/anilist/anilist_api.cpp
    base/anilist/anilist_api.hpp
    base/anilist/anilist_config.hpp
    base/anilist/anilist_entry.cpp
    base/anilist/anilist_entry.hpp
    base/anilist/anilist_keys.hpp
    base/anilist/anilist_media.cpp
    base/anilist/anilist_media.hpp
    base/anilist/anilist_resources.hpp
    base/cache/image_cache.cpp
    base/cache/image_cache.hpp
    base/cache/image_request.cpp
    base/cache/image_request.hpp
    base/database/database.cpp
    base/database/database.hpp
    base/database/database_columns.hpp
    base/database/database_config.hpp
    base/database/database_controller.cpp
    base/database/database_controller.hpp
    base/database/database_keys.hpp
    base/database/database_resources.hpp
    base/logger/logger.cpp
    base/logger/logger.hpp
    base/network/network.cpp
    base/network/network.hpp
    base/recognition/mpris_config.hpp
    base/recognition/mpris_keys.hpp
    base/recognition/mpris_watcher.cpp
    base/recognition/mpris_watcher.hpp
    base/search/search_manager.cpp
    base/search/search_manager.hpp
    base/settings/app_settings.cpp
    base/settings/app_settings.hpp
    base/sync/sync_manager.cpp
    base/sync/sync_manager.hpp
    gui/delegates/anime_list_adult_delegate.cpp
    gui/delegates/anime_list_adult_delegate.hpp
    gui/delegates/anime_list_completed_date_delegate.cpp
    gui/delegates/anime_list_completed_date_delegate.hpp
    gui/delegates/anime_list_completed_date_editor.cpp
    gui/delegates/anime_list_completed_date_editor.hpp
    gui/delegates/anime_list_pending_delegate.cpp
    gui/delegates/anime_list_pending_delegate.hpp
    gui/delegates/anime_list_private_delegate.cpp
    gui/delegates/anime_list_private_delegate.hpp
    gui/delegates/anime_list_progress_delegate.cpp
    gui/delegates/anime_list_progress_delegate.hpp
    gui/delegates/anime_list_progress_editor.cpp
    gui/delegates/anime_list_progress_editor.hpp
    gui/delegates/anime_list_score_delegate.cpp
    gui/delegates/anime_list_score_delegate.hpp
    gui/delegates/anime_list_score_editor.cpp
    gui/delegates/anime_list_score_editor.hpp
    gui/delegates/anime_list_started_date_delegate.cpp
    gui/delegates/anime_list_started_date_delegate.hpp
    gui/delegates/anime_list_started_date_editor.cpp
    gui/delegates/anime_list_started_date_editor.hpp
    gui/delegates/anime_list_status_delegate.cpp
    gui/delegates/anime_list_status_delegate.hpp
    gui/delegates/anime_list_status_editor.cpp
    gui/delegates/anime_list_status_editor.hpp
    gui/delegates/anime_search_adult_delegate.cpp
    gui/delegates/anime_search_adult_delegate.hpp
    gui/delegates/anime_search_in_list_delegate.cpp
    gui/delegates/anime_search_in_list_delegate.hpp
    gui/dialogs/about_dialog.cpp
    gui/dialogs/about_dialog.hpp
    gui/dialogs/anime_info_edit_dialog.cpp
    gui/dialogs/anime_info_edit_dialog.hpp
    gui/dialogs/anime_info_search_dialog.cpp
    gui/dialogs/anime_info_search_dialog.hpp
    gui/dialogs/logger_dialog.cpp
    gui/dialogs/logger_dialog.hpp
    gui/dialogs/login_token_dialog.cpp
    gui/dialogs/login_token_dialog.hpp
    gui/dialogs/set_episode_dialog.cpp
    gui/dialogs/set_episode_dialog.hpp
    gui/dialogs/set_score_dialog.cpp
    gui/dialogs/set_score_dialog.hpp
    gui/list_widget_navigation.cpp
    gui/list_widget_navigation.hpp
    gui/list_widget_separator_delegate.cpp
    gui/list_widget_separator_delegate.hpp
    gui/main_window.cpp
    gui/main_window.hpp
    gui/models/anime_list_model.cpp
    gui/models/anime_list_model.hpp
    gui/models/anime_list_proxy.cpp
    gui/models/anime_list_proxy.hpp
    gui/models/anime_search_model.cpp
    gui/models/anime_search_model.hpp
    gui/models/anime_search_proxy.cpp
    gui/models/anime_search_proxy.hpp
    gui/pages/anime_list_page.cpp
    gui/pages/anime_list_page.hpp
    gui/pages/anime_list_tab_bar.cpp
    gui/pages/anime_list_tab_bar.hpp
    gui/pages/anime_search_page.cpp
    gui/pages/anime_search_page.hpp
    gui/pages/statistics_page.cpp
    gui/pages/statistics_page.hpp
    gui/status_bar.cpp
    gui/status_bar.hpp
    gui/tool_bar_quick_actions.cpp
    gui/tool_bar_quick_actions.hpp
    gui/views/anime_list_header.cpp
    gui/views/anime_list_header.hpp
    gui/views/anime_list_view.cpp
    gui/views/anime_list_view.hpp
    gui/views/anime_search_header.cpp
    gui/views/anime_search_header.hpp
    gui/views/anime_search_view.cpp
    gui/views/anime_search_view.hpp
    gui/widgets/anime_status_combo_box.cpp
    gui/widgets/anime_status_combo_box.hpp
    gui/widgets/date_picker.cpp
    gui/widgets/date_picker.hpp
    gui/widgets/header_view.cpp
    gui/widgets/header_view.hpp
    gui/widgets/infinite_progress_dialog.cpp
    gui/widgets/infinite_progress_dialog.hpp
    gui/widgets/progress_dialog.cpp
    gui/widgets/progress_dialog.hpp
    gui/widgets/spin_box.cpp
    gui/widgets/spin_box.hpp
    main.cpp
    utils/anilist.cpp
    utils/anilist.hpp
    utils/cache.cpp
    utils/cache.hpp
    utils/date.cpp
    utils/date.hpp
    utils/dialog.cpp
    utils/dialog.hpp
    utils/enums.cpp
    utils/enums.hpp
    utils/file.cpp
    utils/file.hpp
    utils/json.cpp
    utils/json.hpp
    utils/links.cpp
    utils/links.hpp
    utils/log.cpp
    utils/log.hpp
    utils/settings.cpp
    utils/settings.hpp
    utils/sync.cpp
    utils/sync.hpp
    utils/web.cpp
    utils/web.hpp
)

target_include_directories(AniTrack
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_compile_definitions(AniTrack
    PRIVATE
        ANITRACK_VERSION="${PROJECT_VERSION}"
)

target_compile_definitions(AniTrack PRIVATE TABLER_ICONS_VERSION="${TABLER_ICONS_VERSION}")

if(ENABLE_WIP_FEATURES)
    message(STATUS "WIP features enabled")
    target_compile_definitions(AniTrack PRIVATE ENABLE_WIP_FEATURES)
    target_compile_definitions(AniTrack PRIVATE ANITOMY_GIT_COMMIT="${ANITOMY_GIT_COMMIT}")
    target_compile_definitions(AniTrack PRIVATE ANIME_RELATIONS_GIT_COMMIT="${ANIME_RELATIONS_GIT_COMMIT}")
endif()

target_sources(AniTrack
    PRIVATE
        gui/dialogs/about_dialog.ui
        gui/dialogs/anime_info_edit_dialog.ui
        gui/dialogs/anime_info_search_dialog.ui
        gui/dialogs/logger_dialog.ui
        gui/dialogs/login_token_dialog.ui
        gui/dialogs/set_episode_dialog.ui
        gui/dialogs/set_score_dialog.ui
        gui/main_window.ui
        gui/pages/anime_list_widget.ui
        gui/pages/anime_search_widget.ui
        gui/pages/statistics_widget.ui
)

qt_add_resources(AniTrack_resources res/resources.qrc)
target_sources(AniTrack
    PRIVATE
        ${AniTrack_resources}
)

target_link_libraries(AniTrack
    PRIVATE
        Qt6::Core
        Qt6::Gui
        Qt6::Widgets
        Qt6::Sql
        Qt6::Network
        Qt6::DBus
        Qt6::Concurrent
        AniTrack-deps
)
